name: "Deploy to Production"

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          script: /opt/website/.github/scripts/deploy.sh
